In [1]:
import numpy as np

In [2]:
import numpy as np

# Problem 2

p2_1 = np.arange(10, 50)

p2_2 = np.arange(9).reshape(3,3)

p2_3 = np.eye(3)

arr30 = np.random.random(30)
p2_4 = arr30.mean()

arr10 = np.random.random((10,10))
p2_5 = arr10.min(), arr10.max()

p2_6 = np.zeros(10)
p2_6[4] = 1

p2_7 = np.array([1,2,0,0,4,0])[::-1]

p2_8 = np.ones((5,5))
p2_8[1:-1,1:-1] = 0

p2_9 = np.zeros((8,8))
p2_9[::2,1::2] = 1
p2_9[1::2,::2] = 1

p2_1, p2_2, p2_3, p2_4, p2_5, p2_6, p2_7, p2_8, p2_9


(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
        27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
        44, 45, 46, 47, 48, 49]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 np.float64(0.5827432610244394),
 (np.float64(0.0007558829163225589), np.float64(0.9822920143634054)),
 array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]),
 array([0, 4, 0, 0, 2, 1]),
 array([[1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.]]))