In [1]:
import numpy as np

In [2]:
import numpy as np

# Problem 4

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

A_inv = np.linalg.inv(A)
proof1 = A @ A_inv

AB = A @ B
BA = B @ A

lhs = (A @ B).T
rhs = B.T @ A.T

A_big = np.array([[2,-3,1],
                  [1,-1,2],
                  [3,1,-1]])

B_big = np.array([-1,-3,9])

sol1 = np.linalg.inv(A_big) @ B_big
sol2 = np.linalg.solve(A_big, B_big)

proof1, AB, BA, lhs, rhs, sol1, sol2


(array([[1.00000000e+00, 0.00000000e+00],
        [1.77635684e-15, 1.00000000e+00]]),
 array([[23, 13],
        [51, 29]]),
 array([[36, 44],
        [13, 16]]),
 array([[23, 51],
        [13, 29]]),
 array([[23, 51],
        [13, 29]]),
 array([ 2.,  1., -2.]),
 array([ 2.,  1., -2.]))