In [1]:
import numpy as np

In [2]:
# Problem 1
# 1
a1 = np.empty((2,2))
# 2
a2 = np.ones((4,2))
# 3
a3 = np.full((3,3), 7)
# 4
given = np.array([[1,2,3],[4,5,6]])
a4 = np.zeros_like(given)
# 5
a5 = np.ones_like(given)
# 6
new_list = [1,2,3,4]
a6 = np.array(new_list)

a1, a2, a3, a4, a5, a6


(array([[5.10667766e-315, 0.00000000e+000],
        [4.94065646e-324, 6.60105314e-310]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]),
 array([[0, 0, 0],
        [0, 0, 0]]),
 array([[1, 1, 1],
        [1, 1, 1]]),
 array([1, 2, 3, 4]))