In [1]:
import numpy as np

In [2]:
# Problem 3

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

p3_1 = x + y
p3_2 = x - y
p3_3 = x * 3
p3_4 = x ** 2

p3_5_vw = np.dot(v,w)
p3_5_xv = np.dot(x,v)
p3_5_xy = np.dot(x,y)

p3_6_xy = np.concatenate((x,y), axis=0)
p3_6_vw = np.column_stack((v,w))

try:
    np.concatenate((x,v))
except Exception as e:
    p3_7 = str(e)
    explanation = "Error: x is 2D but v is 1D."

p3_1, p3_2, p3_3, p3_4, p3_5_vw, p3_5_xv, p3_5_xy, p3_6_xy, p3_6_vw, p3_7, explanation


(array([[ 6,  8],
        [10, 13]]),
 array([[-4, -4],
        [-4, -3]]),
 array([[ 3,  6],
        [ 9, 15]]),
 array([[ 1,  4],
        [ 9, 25]]),
 np.int64(219),
 array([29, 77]),
 array([[19, 22],
        [50, 58]]),
 array([[1, 2],
        [3, 5],
        [5, 6],
        [7, 8]]),
 array([[ 9, 11],
        [10, 12]]),
 'all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)',
 'Error: x is 2D but v is 1D.')